### ISSUE TITLE
Alert SCSS not consumable

### ISSUE THREAD

**Issue by yogeshgadge** [US-CBP/cbp-theme#205]
`_alerts.scss` extends classes from other files without importing. However importing is not the solution since it will create duplication. 

```scss
    .alert-icon {
        @extend .fa;
        margin-right: 3px;
        width: 18px;
        margin-left: -4px;
        text-align: center;
        display: inline-block;
    }
   //lines omitted
  .alert-icon-info{
      @extend .fa-info-circle;
   }
```

In general mixins are preferred over extends however in this case one possible solution for this particular case is:-

Instead of using `alert-icon-info alert-icon` as in  
```
<i class="alert-icon-info alert-icon" aria-hidden="true"></i><span class="sr-only">Info alert</span> Press the <strong>'A'</strong> key to automatically assign a case.
```
we could just use `fa fa-info-circle alert-icon` or something similar i.e. spelling out every class that is necessary.

```
<i class="fa fa-info-circle alert-icon" aria-hidden="true"></i><span class="sr-only">Info alert</span> Press the <strong>'A'</strong> key to automatically assign a case.
```
