### ISSUE TITLE
z-index is different in minified css

### ISSUE THREAD

**Issue by krtools** [US-CBP/cbp-theme#258]
Per #241, I'm using the minified css in 1.10.1, but the z-index values are different from the non-minified version.

Example for modal class:

```scss
// cbp-theme.css:7089
.modal {
  ...
  z-index: 1050;
}
```

```scss
// cbp-theme.min.css:4:303300
.modal {...; z-index: 13;...}
```
There are several other cases where the value is different e.g. `.dropdown-backdrop` has z-index of 12 instead of 1040. 

This is interfering with our custom styles that work with the original z-index values from bootstrap.
